import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { cn, Layout } from '@/components/craft';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          roboto.className
        )}
      >
        {children}
      </body>
    </Layout>
  );
}
